# Generated by Django 5.0.2 on 2024-03-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0004_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
