# Generated by Django 5.0.2 on 2024-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0005_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
