# Generated by Django 5.0.2 on 2024-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0007_notification_reaction_post_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(default='', max_length=500),
        ),
    ]
