# Generated by Django 5.0.2 on 2024-05-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0008_profile_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='middle_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
