# Generated by Django 5.0.2 on 2024-05-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0010_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together=set(),
        ),
    ]
