# Generated by Django 5.0.2 on 2024-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platApp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='imgs/img_profile/default.png', upload_to='imgs/img_profile/'),
        ),
    ]
